#!/usr/bin/python3


class Commands:
    """
    Common user inputs.
    """
    QUIT_APP = "X"
    CHOOSE_GAME_ALQUERQUE = "A"
    CHOOSE_GAME_BAUERNSCHACH = "B"
    CHOOSE_FIRST_PLAYER_ME = "M"
    CHOOSE_FIRST_PLAYER_OPPONENT = "P"
    CHOOSE_OPP_AS_HUMAN = "H"
    CHOOSE_OPP_AS_MACHINE = "C"
    CHOOSE_MACHINE_STRATEGY_RANDOM = "R"
    CHOOSE_MACHINE_STRATEGY_CLEVER = "I"
    CHOOSE_MACHINE_STRATEGY_SIMPLE_HEURISTIC = "S"
    CHOOSE_MACHINE_STRATEGY_COMPLEX_HEURISTIC = "V"
    ABORT_GAME_START_FRESH = "Q"
